export enum GameStateEnum {
    GAME_START = "GAME_START",
    PLAYER_ARRANGE = "PLAYER_ARRANGE",
    PLAYER_ATTACK = "PLAYER_ATTACK",
    WAIT_PLAYER_ARRANGE = "WAIT_PLAYER_ARRANGE",
    WAIT_PLAYER_ATTACK = "WAIT_PLAYER_ATTACK",
    PLAYER1_ARRANGE = "PLAYER1_ARRANGE",
    PLAYER2_ARRANGE = "PLAYER2_ARRANGE",
    PLAYER1_ATTACK = "PLAYER1_ATTACK",
    PLAYER2_ATTACK = "PLAYER2_ATTACK",
    GAME_END = "GAME_END",
};
