export enum GameStateEnum {
    GAME_START = "GAME_START",
    PLAYER_ARRANGE = "PLAYER_ARRANGE",
    PLAYER_ATTACK = "PLAYER_ATTACK",
    WAIT_PLAYER_ARRANGE = "WAIT_PLAYER_ARRANGE",
    WAIT_PLAYER_ATTACK = "WAIT_PLAYER_ATTACK",
    GAME_WIN = "GAME_WIN",
    GAME_LOSE = "GAME_LOSE",
};
