export enum GameStateEnum {
    GAME_START = "GAME_START",
    PLAYER1_ARRANGE = "PLAYER1_ARRANGE",
    PLAYER2_ARRANGE = "PLAYER2_ARRANGE",
    PLAYER1_ATTACK = "PLAYER1_ATTACK",
    PLAYER2_ATTACK = "PLAYER2_ATTACK",
    GAME_END = "GAME_END",
}
